"""Initial migration

Revision ID: d71170c3bf78
Revises: 
Create Date: 2025-02-18 13:29:50.498127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd71170c3bf78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    op.drop_table('users')
    op.drop_table('general_admins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('general_admin_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('investor_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='general_admins_pkey'),
    sa.UniqueConstraint('general_admin_id', name='general_admins_general_admin_id_key')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email_otp', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('email_otp_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('phone_otp', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('phone_otp_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('phone_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('investor_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('interested_in', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('investor_id', name='users_investor_id_key'),
    sa.UniqueConstraint('phone_number', name='users_phone_number_key')
    )
    op.create_table('property',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('property_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('key_features', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('investment_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('available_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='property_pkey')
    )
    # ### end Alembic commands ###
